[package]
name = "download-lp-test"
version = "0.0.1"
authors = ["snsvrno <snsvrno@tuta.io>"]

[dependencies]
download-lp = { path = "../" }
log = "0.4"
pretty_env_logger = "0.3"

[[bin]]
name = "download"
path = "main.rs"